include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_CONTACT "leshgun@github.com")
set(CPACK_PACKAGE_VERSION_MAJOR 1)
set(CPACK_PACKAGE_VERSION_MINOR 0)
set(CPACK_PACKAGE_VERSION_PATCH 0)
set(CPACK_PACKAGE_VERSION "1.0.0")

set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION_SOLVER)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Solver application from lab03")
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)

# Настройки для RPM
set(CPACK_RPM_PACKAGE_NAME "solver-app")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Utility")
set(CPACK_RPM_PACKAGE_RELEASE 1)

# Настройки для DEB
set(CPACK_DEBIAN_PACKAGE_NAME "solver-app")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

include(CPack)
