name: Docker CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t logger .

    - name: Test Docker Container Run
      run: |
        mkdir -p logs
        echo -e "test_ci_1\ntest_ci_2\ntest_ci_3" | docker run -i -v "$(pwd)/logs/:/home/logs/" logger
        cat logs/log.txt
